import type { Metadata } from "next";
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { LanguageProvider } from "@inlang/paraglide-next";
import { languageTag } from "@/paraglide/runtime.js";
import * as m from "@/paraglide/messages.js";
import PrimaryNavigation from "@/components/primary-navigation/primary-navigation";
import LanguageMenu from "@/components/language-menu/language-menu";
import "./globals.css";
import styles from "./layout.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html lang={languageTag()}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <header className={styles.header}>
            <PrimaryNavigation />

            <p>{m.hello_world({ name: "world" })}</p>

            <LanguageMenu />
          </header>

          {children}

          <SpeedInsights />
        </body>
      </html>
    </LanguageProvider>
  );
}
